name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: cd java && mvn install
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: ./java/target/
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      CRAFTJS_ENV: test
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./js
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: "19.3.0.java11"
      - uses: actions/download-artifact@v2
        with:
          name: target
      - name: Cache server
        id: cache-server
        uses: actions/cache@v2
        with:
          path: ./server
          key: ${{ runner.os }}-server
      - name: Setup server
        run: |
          mkdir -p ./server/plugins
          mv ./*.jar ./server/plugins
          mv ./js ./server/js
          cd ./server/js/internal
          npm install
          cd ../..
          wget -c https://papermc.io/api/v1/paper/1.16.1/133/download -O paper.jar
      - name: Run tests
        run: |
          cd server
          java -Dcom.mojang.eula.agree=true -jar paper.jar
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: target
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./*.jar
