name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: cd java && mvn install
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: ./java/target/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: target
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./*.jar
  test-js:
    runs-on: ubuntu-latest
    needs: build
    env:
      CRAFTJS_ENV: test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: target
      - run: |
          mkdir plugins
          mv ./*.jar ./plugins
          wget https://papermc.io/api/v1/paper/1.16.1/133/download -O paper.jar
          ls
          java -jar paper.jar
